// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about: dynamic(() => import("./About")),
  contact: dynamic(() => import("./Contact")),
  courses: dynamic(() => import("./Courses")),
  gallery_images: dynamic(() => import("./GalleryImages")),
  hero: dynamic(() => import("./Hero")),
  team: dynamic(() => import("./Team")),
};
